# Generated by Django 3.0.10 on 2022-08-02 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_actors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actors',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
